/* VENDO AS DATABASES (APENAS MYSQL)*/

SHOW DATABASE;

/* CRIANDO DATABASE */

CREATE DATABASE LIVROS;

/* ALTERNANDO PARA ESSE BANCO DE DADOS */

USE LIVROS;

/* CRIANDO UMA TABELA */

CREATE TABLE LIVRO(
	TITULO VARCHAR(40),
	AUTOR VARCHAR(30),
	GENERO VARCHAR(30),
	EDITORA VARCHAR(30),
	NUMEROPAG INT (4)
				  );	
				 
/* VENDO AS TABELAS */

SHOW TABLES;


/* EXIBINDO DESCRIÇÃO DA TABELA */

DESC LIVRO;


/* INSERINDO DADOS SEM ESPECIFICAR O CAMPO */

INSERT INTO LIVRO VALUES ('SENHOR DOS ANEIS', 'RR TOLKIEN', 'FANTASIA', 'PIPOCA&NANQUIM', 1008);



/*INSERINDO DADOS ESPECIFICANDO O CAMPO */


INSERT INTO LIVRO (TITULO, AUTOR, GENERO, EDITORA, NUMEROPAG) VALUES ( 'DUNA', 'Frank Herbert', 'FICÇÃO CIENTIFICA', 'PIPOCA&NANQUIM', 2005);




/* USANDO O SELECT PARA CONSTRUIR */

SELECT 'FELIPE' AS 'ALUNO';
SELECT NOW();
SELECT NOW() AS 'DATA E HORA';

SELECT 'FELIPE' AS 'ALUNO', NOW() AS 'DATA E HORA';

/* USANDO O SELECT PARA RETORNO DE DADOS */

SELECT TITULO, AUTOR, EDITORA FROM LIVRO;
SELECT GENERO, NUMEROPAG AS 'NUMERO DE PAGINAS' FROM LIVRO;


/* SELECT PARA RETORNAR TODOS OS CAMPOS */

SELECT * FROM LIVRO;

/* FILTRO POR LINHA USANDO WHERE */

SELECT TITULO, GENERO FROM LIVRO
WHERE GENERO = 'FANTASIA';

SELECT AUTOR, NUMEROPAG FROM LIVRO
WHERE TITULO = 'ANEIS'; 


/* USANDO O LIKE ( CONTEEM ) */

SELECT AUTOR, NUMEROPAG FROM LIVRO /* COMEÇA COM QUALQUER COISA E TERMINA COM ANEIS */
WHERE TITULO LIKE '%ANEIS';

SELECT TITULO, NUMEROPAG FROM LIVRO	/* COMEÇA COM RR COISA E TERMINA COM QUALQUER COISA */
WHERE AUTOR LIKE 'RR%';			

SELECT AUTOR, NUMEROPAG FROM LIVRO /* TEM 'DOS' NO MEIO DA FRASE */
WHERE TITULO LIKE '%DOS%';

SELECT AUTOR, NUMEROPAG FROM LIVRO /* '_' IGUAL A CARACTERES, TEM 5 CARACTERES DEPOIS DO 'DOS */
WHERE TITULO LIKE '%DOS____%';